name: Jonah Fuller
favicon: null
layout_spectrum: 0.25406
typography_spectrum: 0.73349
title: Things
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfff6'
    - '#183440'
    - '#3f606f'
    - '#92aa9d'
    - '#d1dcbe'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
