name: Jonah Fuller
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49628
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1e20'
    - '#dc3522'
    - '#374140'
    - '#d9cb9e'
    - '#6d6e73'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
